=== repagh/dueca/gitscripts/default/testscenario.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://dueca.tudelft.nl/testscenario"
  xmlns="https://dueca.tudelft.nl/testscenario"
  elementFormDefault="qualified">

  <xs:element name="scenario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="project" type="project_t"
          minOccurs="1" maxOccurs="1" />
        <xs:element name="repository" type="xs:string"
          minOccurs="1" maxOccurs="1" />
        <xs:element name="version" type="xs:string"
          minOccurs="0" maxOccurs="1" />
        <xs:element name="buildoptions" type="xs:string"
          minOccurs="0" maxOccurs="1" />
        <xs:element name="execute" type="execute_t"
          minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="offset" type="offset_t"
          minOccurs="0" maxOccurs="1" />
        <xs:element name="actions" type="actions_t"
          minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="project_t">
    <xs:sequence>
      <xs:element name="window" type="xs:string"
        minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="execute_t">
    <xs:sequence>
      <xs:element name="platform" type="xs:string"
        minOccurs="1" maxOccurs="1" />
      <xs:element name="node" type="xs:string"
        minOccurs="1" maxOccurs="1" />
      <xs:element name="command" type="xs:string"
        minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="actions_t">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="click" type="click_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="check" type="checkcolor_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="check-image" type="checkimage_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="check-color" type="checkcolor_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="check-word" type="checkword_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="snap" type="snap_t" minOccurs="1" maxOccurs="1" />
      <xs:element name="key" type="key_t" minOccurs="1" maxOccurs="1" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="offset_t">
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="criterion" type="xs:float" />
    <xs:attribute name="template-pattern" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="checkcolor_t">
    <xs:attribute name="window" type="xs:string" />
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="r" type="xs:integer" />
    <xs:attribute name="g" type="xs:integer" />
    <xs:attribute name="b" type="xs:integer" />
    <xs:attribute name="timeout" type="xs:decimal" />
    <xs:attribute name="wait" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="checkimage_t">
    <xs:attribute name="window" type="xs:string" />
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="testsize" type="xs:integer" />
    <xs:attribute name="template" type="xs:string" />
    <xs:attribute name="timeout" type="xs:decimal" />
    <xs:attribute name="wait" type="xs:decimal" />
    <xs:attribute name="criterion" type="xs:float" />
  </xs:complexType>

  <xs:complexType name="checkword_t">
    <xs:attribute name="window" type="xs:string" />
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="testsize" type="xs:integer" />
    <xs:attribute name="word" type="xs:string" />
    <xs:attribute name="timeout" type="xs:decimal" />
    <xs:attribute name="wait" type="xs:decimal" />
    <xs:attribute name="criterion" type="xs:float" />
  </xs:complexType>

  <xs:complexType name="click_t">
    <xs:attribute name="window" type="xs:string" />
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="button" type="xs:string" />
    <xs:attribute name="pressed" type="xs:boolean" />
    <xs:attribute name="relative" type="xs:boolean" />
    <xs:attribute name="wait" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="key_t">
    <xs:attribute name="window" type="xs:string" />
    <xs:attribute name="x" type="xs:integer" />
    <xs:attribute name="y" type="xs:integer" />
    <xs:attribute name="key" type="xs:string" />
    <xs:attribute name="wait" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="snap_t">
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>

</xs:schema>

=== repagh/dueca/test/runtest/simplesimulation.xml
<?xml version='1.0' encoding='UTF-8'?>
<scenario xmlns="https://dueca.tudelft.nl/testscenario" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://dueca.tudelft.nl/testscenario https://dueca.tudelft.nl/schemas/testscenario.xsd">
  <!-- scenario description

    This uses the SimpleSimulation project, which creates a single player.

    To recreate:

    - Calibrate offset, mouse to upper left corner of a window, press F3
    - Operate DUECA/DUSIME state machine to advance
    - Click once to the right, once to the left, in stick window
      - Take a snapshot
    - Operate to off and exit
  -->
  <project name="SimpleSimulation">
    <window>DUECA/DUSIME control panel</window>
    <window>Are you serious?</window>
    <window>HID GUI</window>
    <window>front</window>
  </project>
  <repository>https://github.com/dueca/</repository>
  <buildoptions>-DUSE_GTK3=ON</buildoptions>
  <execute>
    <platform>simlab</platform>
    <node>host</node>
  </execute>
  <execute>
    <platform>simlab</platform>
    <node>igtest</node>
  </execute>
  <offset x="0" y="17" criterion="0.995"/>
  <actions>
    <!-- hold -->
    <!-- calibrate -->
    <check-image window="DUECA/DUSIME control panel" x="461" y="56" template="buttongreensel" testsize="48" timeout="40.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="463" y="92" template="buttongraysel" testsize="48" timeout="10.0" wait="0.5"/>
    <click x="-1" y="-2" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="-1" y="-2" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="463" y="92" template="buttongreensel" testsize="48" timeout="20.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="464" y="126" template="buttongraysel" testsize="48" timeout="10.0" wait="0.5"/>
    <click x="0" y="-2" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="0" y="-2" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="464" y="126" template="buttongreensel" testsize="48" timeout="20.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="462" y="159" template="buttongreensel" testsize="48" timeout="10.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="464" y="196" template="buttongraysel" testsize="48" timeout="10.0" wait="0.5"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="419" y="193" template="buttongraysel" testsize="48" timeout="10.0" wait="0.5"/>
    <click x="-1" y="-3" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="-1" y="-3" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="463" y="194" template="buttongreensel" testsize="48" timeout="10.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="462" y="230" template="buttongraysel" testsize="48" timeout="10.0" wait="0.5"/>
    <click x="-2" y="0" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="-2" y="0" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-color window="HID GUI" x="143" y="100" r="246" g="245" b="244" timeout="10.0" wait="0.5"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-color window="HID GUI" x="47" y="98" r="246" g="245" b="244" timeout="10.0" wait="2.5"/>
    <snap name="simplesimulation000.png"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-color window="HID GUI" x="145" y="98" r="246" g="245" b="244" timeout="10.0" wait="2.5"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-color window="HID GUI" x="46" y="98" r="246" g="245" b="244" timeout="10.0" wait="2.5"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="468" y="194" template="buttongraysel" testsize="48" timeout="10.0" wait="0.5"/>
    <click x="4" y="-2" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="4" y="-2" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="464" y="162" template="buttongraysel" testsize="48" timeout="10.0" wait="0.5"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="0" y="0" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="466" y="91" template="buttongraysel" testsize="48" timeout="10.0" wait="0.5"/>
    <click x="2" y="-3" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="2" y="-3" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="465" y="59" template="buttongraysel" testsize="48" timeout="10.0" wait="0.5"/>
    <click x="1" y="-1" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="1" y="-1" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="465" y="59" template="buttongreensel" testsize="48" timeout="10.0" wait="0.5"/>
    <check-word window="DUECA/DUSIME control panel" x="14" y="11" word="File" testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="-1" y="-1" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="-1" y="-1" button="Button.left" pressed="false" wait="0.3"/>
    <check-image window="DUECA/DUSIME control panel" x="29" y="66" template="quit-blue" testsize="96" timeout="10.0" wait="0.5"/>
    <click relative="true" x="1" y="-1" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="1" y="-1" button="Button.left" pressed="false" wait="0.3"/>
    <check-word window="Are you serious?" x="25" y="51" word="Yes," testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="-2" y="-4" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="-2" y="-4" button="Button.left" pressed="false" wait="0.3"/>
  </actions>
</scenario>

=== repagh/dueca/test/runtest/tmswsfour.xml
<?xml version="1.0" encoding="UTF-8"?>
<scenario xmlns="https://dueca.tudelft.nl/testscenario" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://dueca.tudelft.nl/testscenario https://dueca.tudelft.nl/schemas/testscenario.xsd">
  <!-- scenario description

    This uses the DuecaTestCommunication project in its simplest way possible,
    but with the simulation distributed over four nodes with websocket communication.

    To recreate:

    - The same scenario from tmssolo.xml can be used. Increate timeout for the
      initial wait a bit.

    - Calibrate offset, mouse to upper left corner of a window, press F3
    - Operate DUECA/DUSIME state machine for the central server to work
    - modify the timing for the stop, to give the simulation time to create/
      delete flasher blips
    - operate to off and exit
  -->
  <project name="DuecaTestCommunication">
    <window>DUECA/DUSIME control panel</window>
    <window>Are you serious?</window>
  </project>
  <repository>https://github.com/dueca/</repository>
  <buildoptions>-DUSE_GTK3=ON</buildoptions>
  <execute>
    <platform>udpws-four</platform>
    <node>node4</node>
  </execute>
  <execute>
    <platform>udpws-four</platform>
    <node>node3</node>
  </execute>
  <execute>
    <platform>udpws-four</platform>
    <node>node2</node>
  </execute>
  <execute>
    <platform>udpws-four</platform>
    <node>node1</node>
  </execute>
  <offset x="-2" y="16" criterion="0.995" template-pattern="/gtk3/*.png"/>
  <actions>
    <check-image window="DUECA/DUSIME control panel" x="459" y="58" template="buttongreensel" testsize="64" timeout="30.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="462" y="93" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="2" y="-2" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="2" y="-2" button="Button.left" pressed="false" wait="0.3"/>
    <check-image window="DUECA/DUSIME control panel" x="462" y="93" template="buttongreensel" testsize="64" timeout="30.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="458" y="133" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="-2" y="2" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="-2" y="2" button="Button.left" pressed="false" wait="0.3"/>
    <check-image window="DUECA/DUSIME control panel" x="458" y="133" template="buttongreensel" testsize="64" timeout="20.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="459" y="161" template="buttongreensel" testsize="64" timeout="10.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="460" y="197" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="0" y="-4" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="0" y="-4" button="Button.left" pressed="false" wait="0.3"/>
    <check-image window="DUECA/DUSIME control panel" x="462" y="201" template="buttongreensel" testsize="64" timeout="10.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="418" y="198" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="2" y="-3" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="2" y="-3" button="Button.left" pressed="false" wait="0.3"/>
    <check-image window="DUECA/DUSIME control panel" x="418" y="198" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="459" y="235" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="-1" y="0" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="-1" y="0" button="Button.left" pressed="false" wait="0.3"/>
    <snap name="tmssolo000.png"/>
    <check-image window="DUECA/DUSIME control panel" x="458" y="201" template="buttongraysel" testsize="64" timeout="10.0" wait="8.5"/>
    <click relative="true" x="-2" y="0" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="-2" y="0" button="Button.left" pressed="false" wait="0.3"/>
    <check-image window="DUECA/DUSIME control panel" x="463" y="167" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="3" y="0" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="3" y="0" button="Button.left" pressed="false" wait="0.3"/>
    <check-image window="DUECA/DUSIME control panel" x="461" y="127" template="buttongreensel" testsize="64" timeout="10.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="462" y="93" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="2" y="-2" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="2" y="-2" button="Button.left" pressed="false" wait="0.3"/>
    <check-image window="DUECA/DUSIME control panel" x="459" y="59" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="-1" y="-2" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="-1" y="-2" button="Button.left" pressed="false" wait="0.3"/>
    <check-image window="DUECA/DUSIME control panel" x="459" y="59" template="buttongreensel" testsize="64" timeout="10.0" wait="0.5"/>
    <check-word window="DUECA/DUSIME control panel" x="14" y="11" word="File" testsize="64" timeout="10.0" wait="0.5" criterion="30"/>
    <click relative="true" x="-1" y="-1" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="-1" y="-1" button="Button.left" pressed="false" wait="0.3"/>
    <check-image window="DUECA/DUSIME control panel" x="29" y="66" template="quit-blue" testsize="96" timeout="10.0" wait="0.5"/>
    <click relative="true" x="1" y="-1" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="1" y="-1" button="Button.left" pressed="false" wait="0.3"/>
    <check-word window="Are you serious?" x="25" y="51" word="Yes," testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="-2" y="-4" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="-2" y="-4" button="Button.left" pressed="false" wait="0.3"/>
  </actions>
</scenario>

=== repagh/dueca/test/runtest/triggering.xml
<?xml version='1.0' encoding='UTF-8'?>
<scenario xmlns="https://dueca.tudelft.nl/testscenario" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://dueca.tudelft.nl/testscenario https://dueca.tudelft.nl/schemas/testscenario.xsd">
  <!-- scenario description

    This uses the DuecaTestCommunication project to check some triggering logic.

    To recreate:

    - Calibrate offset, mouse to upper left corner of a window, press F3
    - Operate DUECA/DUSIME state machine to work
    - modify the timing for the stop, to give the simulation time to run the
      code
    - operate to off and exit
  -->
  <project name="DuecaTestCommunication">
    <window>DUECA/DUSIME control panel</window>
    <window>Are you serious?</window>
    <window>Activity View</window>
  </project>
  <repository>https://github.com/dueca/</repository>
  <buildoptions>-DUSE_GTK3=ON</buildoptions>
  <execute>
    <platform>solo</platform>
    <node>triggering</node>
  </execute>
  <actions>
    <check-image window="DUECA/DUSIME control panel" x="461" y="41" template="buttongreensel" testsize="64" timeout="10.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="463" y="75" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click x="-1" y="-2" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="-1" y="-2" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="463" y="75" template="buttongreensel" testsize="64" timeout="10.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="465" y="109" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click x="1" y="-2" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="1" y="-2" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="465" y="109" template="buttongreensel" testsize="64" timeout="10.0" wait="20.5"/>
    <snap name="triggering000.png"/>
    <check-image window="DUECA/DUSIME control panel" x="463" y="75" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click x="-1" y="-2" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="-1" y="-2" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="463" y="75" template="buttongreensel" testsize="64" timeout="10.0" wait="0.5"/>
    <check-image window="DUECA/DUSIME control panel" x="463" y="39" template="buttongraysel" testsize="64" timeout="10.0" wait="0.5"/>
    <click x="-1" y="-4" relative="true" button="Button.left" pressed="true" wait="0.2"/>
    <click x="-1" y="-4" relative="true" button="Button.left" pressed="false" wait="0.2"/>
    <check-image window="DUECA/DUSIME control panel" x="463" y="39" template="buttongreensel" testsize="64" timeout="10.0" wait="0.5"/>
    <check-word window="DUECA/DUSIME control panel" x="14" y="11" word="File" testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="-1" y="-1" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="-1" y="-1" button="Button.left" pressed="false" wait="0.3"/>
    <check-image window="DUECA/DUSIME control panel" x="29" y="66" template="quit-blue" testsize="96" timeout="10.0" wait="0.5"/>
    <click relative="true" x="1" y="-1" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="1" y="-1" button="Button.left" pressed="false" wait="0.3"/>
    <check-word window="Are you serious?" x="25" y="51" word="Yes," testsize="64" timeout="10.0" wait="0.5"/>
    <click relative="true" x="-2" y="-4" button="Button.left" pressed="true" wait="0.3"/>
    <click relative="true" x="-2" y="-4" button="Button.left" pressed="false" wait="0.3"/>
  </actions>
</scenario>
